name: Build EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: TvG
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pyinstaller
      - run: pyinstaller Game.spec
      - uses: actions/upload-artifact@v4
        with:
          name: TanksVsGuys
          path: TvG/dist/TanksVsGuys.exe
